import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-slate-200`}>
      <div className="flex">
        <Sidebar/>
        <div className="flex flex-col w-full">
          <Header/>
          <main className="p-2">{children}</main>
        </div>
      </div>
      </body>
    </html>
  );
}
